# frozen_string_literal: true

require 'active_support/concern'
require 'securerandom'

module OpenehrRails
  # Persists model data as a canonical openEHR RM Composition document.
  #
  # Including models are generated by `rails g openehr:scaffold` and define:
  #   TEMPLATE_ID       - openEHR template id
  #   ROOT_ARCHETYPE_ID - archetype id of the COMPOSITION root
  #   FIELD_MAP         - {attribute_name => field description} where the
  #                       field description matches Opt::FieldExtractor output
  #
  # The typed columns stay the source for Rails forms and queries; the
  # rm_composition JSON column is refreshed on every save and is the
  # canonical openEHR representation (used by AQL and the FHIR facade).
  module Storable
    extend ActiveSupport::Concern

    # RM attributes with multiple cardinality become JSON arrays.
    MULTIPLE_ATTRIBUTES = %w[content events items activities].freeze

    included do
      before_save :refresh_rm_composition
      after_save :persist_rm_graph
      after_destroy :purge_rm_graph
      OpenehrRails::Fhir::ResourceRegistry.register_model(self)
    end

    class_methods do
      # Builds a new (unsaved) record from a canonical RM Composition hash.
      def from_rm_composition(composition)
        new(attributes_from_rm_composition(composition))
      end

      def attributes_from_rm_composition(composition)
        composition = composition.deep_stringify_keys if composition.respond_to?(:deep_stringify_keys)
        const_get(:FIELD_MAP).each_with_object({}) do |(name, field), attrs|
          value_node = dig_rm_path(composition, field)
          next if value_node.nil?

          attrs[name] = rm_value_to_attribute(value_node, field)
        end
      end

      private

      def dig_rm_path(composition, field)
        segments = OpenehrRails::Storable.path_segments(field[:path])
        node = composition
        segments.each do |attribute, node_id|
          return nil if node.nil?
          next node = node[attribute] if attribute == 'value'

          child = node[attribute]
          child = Array(child).find { |c| c['archetype_node_id'] == node_id } if child.is_a?(Array)
          node = child
        end
        node
      end

      def rm_value_to_attribute(value_node, field)
        return value_node unless value_node.is_a?(Hash)

        case field[:rm_type]
        when 'DV_QUANTITY', 'DV_COUNT', 'DV_PROPORTION'
          value_node['magnitude']
        when 'DV_CODED_TEXT'
          value_node.dig('defining_code', 'code_string') || value_node['value']
        else
          value_node['value']
        end
      end
    end

    # Head version of the persisted RM graph (nil when the RM persistence
    # layer is disabled or its tables are absent).
    def rm_graph
      return nil unless rm_layer_available?

      OpenehrRails::Rm::Composition.latest.find_by(owner_type: self.class.name, owner_id: id)
    end

    def to_rm_composition
      composition = {
        '_type' => 'COMPOSITION',
        'archetype_node_id' => self.class::ROOT_ARCHETYPE_ID,
        'archetype_details' => {
          '_type' => 'ARCHETYPED',
          'archetype_id' => { 'value' => self.class::ROOT_ARCHETYPE_ID },
          'template_id' => { 'value' => self.class::TEMPLATE_ID },
          'rm_version' => '1.0.4'
        },
        'content' => rm_content
      }
      composition['uid'] = { '_type' => 'HIER_OBJECT_ID', 'value' => uid } if respond_to?(:uid) && uid
      composition
    end

    # Splits an RM path into [attribute, node_id] pairs:
    # "/content[x]/data[at0001]/value" => [["content","x"],["data","at0001"],["value",nil]]
    def self.path_segments(path)
      path.scan(%r{/([^/\[]+)(?:\[([^\]]+)\])?}).map { |attr, node| [attr, node] }
    end

    private

    def persist_rm_graph
      return unless rm_layer_available?

      OpenehrRails::Rm::GraphPersister.persist(self)
    end

    def purge_rm_graph
      return unless rm_layer_available?

      OpenehrRails::Rm::GraphPersister.purge(self)
    end

    def rm_layer_available?
      defined?(OpenehrRails::Rm) && OpenehrRails::Rm.enabled?
    end

    def refresh_rm_composition
      self.uid ||= SecureRandom.uuid if respond_to?(:uid=)
      self.composed_at ||= Time.current if respond_to?(:composed_at=)
      self.template_id ||= self.class::TEMPLATE_ID if respond_to?(:template_id=)
      self.rm_composition = to_rm_composition if respond_to?(:rm_composition=)
    end

    def rm_content
      entries = {}
      self.class::FIELD_MAP.each do |name, field|
        field = field.merge(name: name.to_s)
        value = public_send(name)
        next if value.nil?

        entry = entries[field[:archetype_id]] ||= {
          '_type' => field[:entry_rm_type],
          'archetype_node_id' => field[:archetype_id],
          'archetype_details' => {
            '_type' => 'ARCHETYPED',
            'archetype_id' => { 'value' => field[:archetype_id] },
            'rm_version' => '1.0.4'
          }
        }
        insert_rm_value(entry, field, value)
      end
      entries.values
    end

    def insert_rm_value(entry, field, value)
      segments = OpenehrRails::Storable.path_segments(field[:path])
      segments = segments[1..] # the leading /content[...] is the entry itself
      node = entry
      segments.each do |attribute, node_id|
        if attribute == 'value'
          node['_type'] ||= 'ELEMENT'
          node['value'] = rm_value(field, value)
        elsif MULTIPLE_ATTRIBUTES.include?(attribute)
          # A node holding 'items' that wasn't typed by the 'data' rule is a
          # nested CLUSTER (ELEMENTs are typed by the 'value' branch).
          node['_type'] ||= 'CLUSTER' if attribute == 'items'
          siblings = node[attribute] ||= []
          node = siblings.find { |s| s['archetype_node_id'] == node_id } ||
                 (siblings << new_rm_node(attribute, node['_type'] || entry['_type'], node_id)).last
        else
          node = node[attribute] ||= new_rm_node(attribute, node['_type'] || entry['_type'], node_id)
        end
      end
    end

    # Infers the RM type of an intermediate node from the attribute it
    # fills and the parent's type. 'items' children stay untyped here: the
    # 'value' branch marks ELEMENTs and the 'items' descent marks CLUSTERs.
    def new_rm_node(attribute, parent_type, node_id)
      rm_type =
        case attribute
        when 'data'
          parent_type == 'OBSERVATION' ? 'HISTORY' : 'ITEM_TREE'
        when 'events' then 'POINT_EVENT'
        when 'state', 'protocol', 'description' then 'ITEM_TREE'
        when 'activities' then 'ACTIVITY'
        end
      node = {}
      node['_type'] = rm_type if rm_type
      node['archetype_node_id'] = node_id
      node
    end

    def rm_value(field, value)
      case field[:rm_type]
      when 'DV_QUANTITY'
        units_attribute = "#{field[:name]}_units"
        units = respond_to?(units_attribute) ? public_send(units_attribute) : nil
        { '_type' => 'DV_QUANTITY', 'magnitude' => value.to_f, 'units' => units || field[:units] }
      when 'DV_COUNT'
        { '_type' => 'DV_COUNT', 'magnitude' => value.to_i }
      when 'DV_PROPORTION'
        { '_type' => 'DV_PROPORTION', 'numerator' => value.to_f, 'denominator' => 1, 'type' => 1 }
      when 'DV_CODED_TEXT'
        {
          '_type' => 'DV_CODED_TEXT',
          'value' => field[:code_labels]&.fetch(value, value) || value,
          'defining_code' => {
            '_type' => 'CODE_PHRASE',
            'terminology_id' => { 'value' => field[:terminology_id] || 'local' },
            'code_string' => value
          }
        }
      when 'DV_BOOLEAN'
        { '_type' => 'DV_BOOLEAN', 'value' => value }
      when 'DV_DATE', 'DV_TIME', 'DV_DATE_TIME'
        time_value = value.respond_to?(:iso8601) ? value.iso8601 : value.to_s
        { '_type' => field[:rm_type], 'value' => time_value }
      else
        { '_type' => 'DV_TEXT', 'value' => value.to_s }
      end
    end
  end
end
