# syntax=docker/dockerfile:1
#
# Builds and runs the openehr-rails demo app (see doc/DEMO_ja.md) end to
# end from a container, with no local Ruby/Rails setup required beyond
# Docker. Runs in development mode on purpose: the admin engine's runtime
# scaffolding (the "Generate UI" button, URL import) is gated to
# non-production environments by OpenehrRails.runtime_scaffolding_allowed?,
# and this image exists to demonstrate that workflow -- it is not a
# hardened production deployment. (demo/Dockerfile, generated by
# `rails new`, is that -- but it isn't usable standalone here since its
# Gemfile references the gem via `path: ".."`, which only resolves inside
# this repo; script/build_starter.sh's generated repos swap that for a
# real gem dependency instead.)
#
# Build & run from the repo root:
#   docker compose -f docker/docker-compose.yml up --build
# or directly:
#   docker build -f docker/demo.Dockerfile -t openehr-rails-demo .
#   docker run -p 3000:3000 -v openehr-rails-demo-storage:/rails/demo/storage openehr-rails-demo

ARG RUBY_VERSION=4.0.6

FROM docker.io/library/ruby:${RUBY_VERSION}-slim AS build

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential git libffi-dev libsqlite3-dev libyaml-dev pkg-config curl && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

RUN gem install rails bundler --no-document

WORKDIR /rails
COPY . .

RUN FORCE=1 bash script/build_demo.sh
RUN rm -rf /rails/coverage

FROM docker.io/library/ruby:${RUBY_VERSION}-slim

# openehr-rails.gemspec shells out to `git ls-files` to build gem.files,
# and Bundler re-evaluates every path-referenced gemspec on each Rails
# boot (not just at `bundle install` time) -- so both .git and the git
# binary have to survive into the runtime image, not just the build stage.
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y git libsqlite3-0 && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives/*

ENV RAILS_ENV=development \
    BUNDLE_PATH=/usr/local/bundle

WORKDIR /rails/demo
COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --from=build /rails /rails

EXPOSE 3000
CMD ["bin/rails", "server", "-b", "0.0.0.0"]
